TEST_ENV_CONFIG = {
    "AWS_DEFAULT_REGION": "us-west-2",
    "WORKERS_PER_CPU": "1",
    "JOB_TABLE": "TEST-JOB-TABLE",
    "FEATURE_TABLE": "TEST-FEATURE-TABLE",
    "IMAGE_QUEUE": "TEST-IMAGE-QUEUE",
    "REGION_QUEUE": "TEST-REGION-QUEUE",
}
