---
block-list-secret-scan: []
branch: master
directory:
- .
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- all
mask: []
secrets-history-timeout: 12h
secrets-scan-file-type: []
summary-position: top
skip-check:
  # Ensure that certificate validation isn't disabled with the pip '--trusted-host' option
  # Reason: We are not disabling certificate validation, we are trusting a
  # specific host that is provided by the customer for package installations.
  - CKV2_DOCKER_4
