name: 'Generate Deployment JSON'
description: 'Generate deployment.json from example template'
inputs:
  account_id:
    description: 'AWS account ID'
    required: true
  region:
    description: 'AWS region'
    required: true
runs:
  using: composite
  steps:
    - name: Generate deployment.json
      working-directory: cdk
      shell: bash
      env:
        ACCOUNT_ID: ${{ inputs.account_id }}
        REGION: ${{ inputs.region }}
      run: |
        python3 << 'EOF'
        import json
        import os
        with open('bin/deployment/deployment.json.example') as f:
            config = json.load(f)
        config['account']['id'] = os.environ['ACCOUNT_ID']
        config['account']['region'] = os.environ['REGION']
        with open('bin/deployment/deployment.json', 'w') as f:
            json.dump(config, f, indent=2)
        EOF
